SUB
  SUB
    SUB
      SUB
        SUB
          HUE
          DIV
            RED
            ADD
              CONST 76.698921
              BLUE
        DIV
          DIV
            CONST 40.723839
            BLUE
          DIV
            LIGHTNESS
            ADD
              RED
              DIV
                DIV
                  VALUE
                  LUMINOSITY
                DIV
                  RAND
                    MUL
                      CONST 78.415939
                      SUB
                        CONST 78.415939
                        VALUE
                    SUB
                      DIV
                        LUMINOSITY
                        HSV_SAT
                      ADD
                        BLUE
                        CONST 40.723839
                  ADD
                    ADD
                      DIV
                        VALUE
                        HUE
                      BLUE
                    DIV
                      VALUE
                      RAND
                        SUB
                          DIV
                            VALUE
                            HSV_SAT
                          RAND
                            SUB
                              MUL
                                DIV
                                  DIV
                                    GREEN
                                    RAND
                                      SUB
                                        SUB
                                          HUE
                                          DIV
                                            RED
                                            ADD
                                              CONST 76.698921
                                              BLUE
                                        DIV
                                          DIV
                                            CONST 40.723839
                                            RAND
                                              SUB
                                                ADD
                                                  SUB
                                                    DIV
                                                      VALUE
                                                      DIV
                                                        ADD
                                                          LUMINOSITY
                                                          RED
                                                        ADD
                                                          LUMINOSITY
                                                          RED
                                                    ADD
                                                      LIGHTNESS
                                                      MUL
                                                        RED
                                                        RED
                                                  MUL
                                                    CONST 25.176573
                                                    SUB
                                                      ADD
                                                        CONST 65.893211
                                                        GREEN
                                                      DIV
                                                        HUE
                                                        HUE
                                                DIV
                                                  RAND
                                                    MUL
                                                      HSL_SAT
                                                      VALUE
                                                    DIV
                                                      ADD
                                                        CONST 76.698921
                                                        BLUE
                                                      ADD
                                                        VALUE
                                                        CONST 26.196917
                                                  HSV_SAT
                                              GREEN
                                          DIV
                                            LIGHTNESS
                                            ADD
                                              VALUE
                                              RAND
                                                GREEN
                                                HSV_SAT
                                      GREEN
                                  DIV
                                    LIGHTNESS
                                    ADD
                                      RED
                                      DIV
                                        DIV
                                          VALUE
                                          RAND
                                            SUB
                                              SUB
                                                HSV_SAT
                                                DIV
                                                  HUE
                                                  HUE
                                              RAND
                                                GREEN
                                                RED
                                            DIV
                                              RAND
                                                BLUE
                                                HUE
                                              ADD
                                                LUMINOSITY
                                                RED
                                        DIV
                                          RAND
                                            MUL
                                              ADD
                                                BLUE
                                                HUE
                                              SUB
                                                CONST 78.415939
                                                VALUE
                                            SUB
                                              DIV
                                                LUMINOSITY
                                                HSV_SAT
                                              ADD
                                                BLUE
                                                RED
                                          DIV
                                            VALUE
                                            RAND
                                              SUB
                                                DIV
                                                  VALUE
                                                  HSV_SAT
                                                RAND
                                                  GREEN
                                                  SUB
                                                    DIV
                                                      LUMINOSITY
                                                      HSV_SAT
                                                    ADD
                                                      BLUE
                                                      RED
                                              DIV
                                                RAND
                                                  BLUE
                                                  HUE
                                                ADD
                                                  LUMINOSITY
                                                  RED
                                ADD
                                  RAND
                                    GREEN
                                    HUE
                                  RED
                              SUB
                                DIV
                                  RAND
                                    SUB
                                      MUL
                                        DIV
                                          DIV
                                            CONST 40.723839
                                            RAND
                                              SUB
                                                SUB
                                                  RED
                                                  DIV
                                                    RED
                                                    ADD
                                                      CONST 76.698921
                                                      BLUE
                                                DIV
                                                  DIV
                                                    CONST 40.723839
                                                    RAND
                                                      SUB
                                                        ADD
                                                          SUB
                                                            DIV
                                                              VALUE
                                                              DIV
                                                                ADD
                                                                  LUMINOSITY
